### ISSUE TITLE
A stable connection to the server could not be established

### ISSUE THREAD

**Issue by insideouting** [Airmail/Airmail_Public#101]
I really like your mailer and using it took but a few months ago

From 2 days ago I have an error "A stable connection to the server Could not be established"
I use three imap accounts (not gmail)
The error only comes to me mavericks osx boot and automatically start the application.
Three windows appear with the error in the three accounts
If I start the application manually after osx booted no problem.
I have Airmail in a mac book pro with mavericks and no problem.

I tried the beta version but does not solve the error

What I can do?

Thanks for your help

**Comment by patefilo** [comment]
I have the same problem here today : "A stable connection to the server could not be established."
Neither SSL nor TLS work for me.

**Comment by ianhakes** [comment]
+1 from me too on the solution from @qnm - much obliged!

**Comment by studioraygun** [comment]
@qnm solution also worked for me but i'm still not convinced. It's slow as hell. 

Airmail failed on two Macs on the same day - what gives?

**Comment by ahmet2106** [comment]
@studioraygun on my mac it is really slow to, needs somehow 1 minute to send a mail.. Cant be a SMTP Issue, because these are working on other Mail Clients. Airmail Support does not answer me, too..

**Comment by Mydly** [comment]
+1. Me too. Resetting the simulator can solve the problem.However , it is so troublesome in a appcation.
Is there other solutions?

**Comment by adcoutts** [comment]
Yep, just started happening to me today too. Port 587 and start TLS were already selected prior to it happening. Have tried SSL and Auto and still no joy. Looks like it's back to Apple Mail for me :(

**Comment by adcoutts** [comment]
I shut my Mac down and left it over night. This morning when I booted and restarted Airmail, my emails are sending again. Not a very technical answer to the problem, but in this case it appears the "if in doubt re--start" may be part of the answer.

Note: I had restarted a couple of times to try to resolve the problem before, to no avail. Maybe shutting down and re-starting after 6-8 hours made the difference.

**Comment by do-web** [comment]
same issue here

**Comment by janthurau** [comment]
got the same issue from today on :-(

**Comment by carriercomm** [comment]
New user - however, I have two accounts on two different instances of Exchange. One keeps saying it cannot establish a stable connection, the other says my version of Exchange is outdated.

Hate to say it but this kind of thing is ridiculous. Email connectivity is dead simple - even for programmers building an application. The fact you guys can't seem to fix this issue on iOS doesn't give me the least amount of confidence.

I will give you guys another shot in the near future. We have 500+ systems and I'm looking at possible email clients. However, as I said, this is the kind of mess seen on the first beta. Not something with the sheer amount of time you guys have had to resolve this problem.
