### ISSUE TITLE
Second half of some long emails is cut off by blank white screen

### ISSUE THREAD

**Issue by greiss122** [Airmail/Airmail_Public#114]
Hello, 
Sometimes, when I am scrolling a long or long-ish email, the rest of the email is blank and white. I can see the rest by clicking and dragging above the white part, which then lets me see the bottom of the email but not the top. It's hard to explain, but here are some photos. First is the beginning of the message, then I scroll down, then I drag down. Advice?
![screen shot 2014-01-18 at 12 46 05 am](https://f.cloud.github.com/assets/6404738/1946544/403142ec-800e-11e3-9428-e2d251917603.png)

![screen shot 2014-01-18 at 12 46 16 am](https://f.cloud.github.com/assets/6404738/1946549/58b3c6fa-800e-11e3-89ca-5bb32fe71d95.png)

![screen shot 2014-01-18 at 12 46 41 am](https://f.cloud.github.com/assets/6404738/1946550/6197232a-800e-11e3-8b9a-00eccb655e36.png)

**Comment by digitalmaster** [comment]
@greiss122 Was this ever resolved? I've always had this issue and it's still the case with Airmail 2. Before this I thought it was an optimization (to only download half of the email) but then i noticed there was no "Load Full Message" button anywhere AND if you just click on the mail again it loads correctly.

+1 #bump

**Comment by greiss122** [comment]
No, it never was resolved unfortunately. Not sure why @Bloophub closed the thread. I've always had the issue as well, it's pretty annoying!

**Comment by digitalmaster** [comment]
Yup.. agreed.

**Comment by erwinelling** [comment]
+1. I often have the same problem. @Bloophub

**Comment by daneclarkcollins** [comment]
+1. I switched to another app for a while because this is so frustrating...switched back to Airmail the other day and was reminded why I switched in the first place.

**Comment by digitalmaster** [comment]
@daneclarkcollins same here: I've been using Nylas N1 for a few weeks now..pretty solid, free and open source. But i update Airmail form time to time to see if they've resolved some of these issues.

**Comment by Bloophub** [comment]
beside the fact that is proxy all your mailboxes...

**Comment by publicarray** [comment]
@Bloophub not necessarily. You always have the option to run the Nylas Sync Engine locally. I guess few do though.

**Comment by greiss122** [comment]
You know, I may have to switch from airmail as well.
There are lots of little issues like this and this: (https://github.com/Airmail/Airmail_Public/issues/115#issuecomment-150098307)
That are annoyances but not huge deals. However, when they go unresolved for an entire year,  and are continuously marked closed and fixed as both of these have been, I lose confidence in the developers, and in the app to reliably send important email.
@Bloophub

**Comment by cemarriott** [comment]
Still having this issue with Airmail 2.6.1. I keep coming back because I want to use Airmail but what's the point when half of every other email is blank?

**Comment by ninjatux** [comment]
why this issue is closed? bug is still there, not fixed in `2.6.1`.

**Comment by RogWilco** [comment]
I've been experiencing this issue as well, and it has seem to have gone unaddressed for at least a year or so. I keep waiting to see if an update will fix it and finally caved and started searching to see if anyone else was discussing the same problem.

Then I stumble onto this ticket and find it closed? Ignoring the problem isn't going to make it go away...
