### ISSUE TITLE
Cannot click links to go to different parts of message anymore

### ISSUE THREAD

**Issue by greiss122** [Airmail/Airmail_Public#115]
Hello,
I subscribe to a variety of email newsletters that have a list of the posts included at the top, then little summaries below. There are sometimes more than 50 links in one message, so it is incredibly helpful to be able to click the link at the top to take me to the part of the message with the summary. This USED to work fine in Airmail, just as it does in Gmail, but now I just get this message when I click one:

![screen shot 2014-01-18 at 12 55 17 am](https://f.cloud.github.com/assets/6404738/1946556/e1972412-800e-11e3-80c2-3eaa259b64af.png)

Any advice?
Thanks

**Comment by greiss122** [comment]
Hi,
You closed this issue, but did not fix the problem. Yes, nothing pops up anymore, but airmail still does not move to that part of the message. Please address.
Thanks

**Comment by Bloophub** [comment]
please attache the EML

**Comment by greiss122** [comment]
Attached. The summary links are on top, and you should be able to click one of them to jump down to the right spot. When you quick look preview the EML file on the desktop, that even works.
Thanks for your effort!
-Gabe
http://infinit.gabereiss.com/_/3eZGmJK

**Comment by Bloophub** [comment]
Ok thanks Replicated!

**Comment by greiss122** [comment]
I noticed you closed the thread–will this feature be in the next beta?
Thanks!

**Comment by Bloophub** [comment]
Yes, we did that fix, but let me check again

**Comment by greiss122** [comment]
Hmm. Looks like even in the latest beta it's still a problem. Can you check again? Thanks!
-Gabe
