### ISSUE TITLE
Sending from account Alias creates duplicate emails

### ISSUE THREAD

**Issue by obfuscode** [Airmail/Airmail_Public#116]
When sending from an account "Alias", Airmail creates two emails in the Sent folder (causing duplicates in all "Conversations").

Recipients do NOT receive two emails.

See attached image - "hi@" is my primary account, "hello@" is my Alias address. "hello@" is registered in Gmail as a confirmed "Send Mail As" address (see screenshot 2).

I have tried this with the "hello@" as both "default" and "not default".

![another_test_email_and_another_test_email-17](https://f.cloud.github.com/assets/2160089/1946910/90dedb6a-8030-11e3-9c9a-0fca0ac28e43.jpg)

![settings_-_hi_jace_is_-_mail-5](https://f.cloud.github.com/assets/2160089/1946925/b4f58d90-8031-11e3-91d1-5d46e7427d7f.jpg)

**Comment by Jitan** [comment]
Thanks had the same problem!
