### ISSUE TITLE
Reply isn't including latest message text when attachments are involved

### ISSUE THREAD

**Issue by robalan** [Airmail/Airmail_Public#140]
When I reply to some messages that arrive with attachments, the message text is not included as a quote in the thread. One of the messages simply lists the attachment filename, the other skips the latest message as if I'm responding to the message before it. Version 1.3.1 (223) on OS X 10.9.1.

**Comment by sam-untapt** [comment]
This bug appears to be back in Airmail 3. I upgraded to 3 today, as recommended, and replies with attachments do not include the original message. Replies without attachments are fine.

Forwarding includes the attachment but no email message.

**Comment by xbogdan** [comment]
Same thing happens to me. Is there a way to fix it ?

**Comment by icondesign** [comment]
Happening for me too on v 3

**Comment by ChristianVermeulen** [comment]
Yup, same here! +1
