### ISSUE TITLE
Blank messages, missing to, from, subject fields

### ISSUE THREAD

**Issue by zacwitte** [Airmail/Airmail_Public#172]
The strangest thing started happening with one of the accounts (gmail) I have connected to airmail. all messages coming in on that account have no subject, to field, from and the body is perpetually "Loading". However when I go to the gmail web interface those messages are completely normal. Also the other Google Apps account I have connected still works.

Screenshot:
https://www.dropbox.com/s/mlhfvuqzy6pnewd/Screenshot%202014-01-23%2011.31.06.png

**Comment by dvdsmpsn** [comment]
Me too:

![](https://dl.dropboxusercontent.com/u/658119/tmp/airmail-blank-messages.png)

**Comment by asomorjai** [comment]
From: filed is missing in my case.

**Comment by contra** [comment]
Also getting this problem, any solutions?

**Comment by Bloophub** [comment]
rebuild the account DB

**Comment by contra** [comment]
@Bloophub thanks that fixed it
