### ISSUE TITLE
Credentials Issue Prevent sending mails

### ISSUE THREAD

**Issue by Tataniel** [Airmail/Airmail_Public#180]
I keep having this annoying issue when sending mails!
"Cannot send mail error contact Unable to authenticate with the current session's credentials."
So am not able to send any email, even after verifying my mail and password in all accounts

**Comment by gavrilobozovic** [comment]
I had the same issue when we switched wi-fis, and that on only one mailbox, the other was fine. Both are non-exchange, non-gmail stuff.

In the preferences of the account, I tried testing the SMTP on the faulty mailbox which returned an error. When I changed the authentication from PLAIN to LOGIN, running the SMTP test says that the settings are valid, however, the error only changes. Now it just says:

Cannot send mail error SUBJECT An error occurred while sending the message.

I'm with Airmail 2.0.3. Any clue as to how to solve that?

**Comment by michaelmarkwang** [comment]
Same problem here too with 2.0.3. It keep popping up and restart would solve the problem

**Comment by gavrilobozovic** [comment]
Hello,

Thanks for your message. I am currently away from the office with limited e-mail access. Your message will be read and processed on August 13th.

For any urgent matter, please contact Cem Sever, at cem@restons-serieux.com

Best,

Gavrilo Bozovic


------


Bonjour,

Merci pour votre message. Je suis actuellement absent de mon bureau, avec accès limité à mes e-mails. Votre message sera lu et traité le 13 Août.

Pour toute demande urgente, merci de prendre contact avec Cem Sever, à cem@restons-serieux.com.

Meilleures salutations,

Gavrilo Bozovic

**Comment by oeed** [comment]
This is _not_ fixed. Latest beta, iCloud account, I've tried on multiple machines, multiple wi-fi networks, including a fresh OS X install.
