### ISSUE TITLE
can not click the button

### ISSUE THREAD

**Issue by ghost** [Airmail/Airmail_Public#181]
Hi, please look at the attach image, I got an email from instagram.com for resetting my password, but the button of resetting password can not be clicked, it works on web or other mail client, so please have a check.

![screen shot 2014-01-25 at 5 09 14 pm](https://f.cloud.github.com/assets/1096124/2001328/b1c7ceca-85a0-11e3-902f-fe589cd742c0.png)

**Comment by jtagen** [comment]
I see this frequently, very frustrating. Facebook notifications also fall into this category, you can click the buttons in most email clients, but not Airmail.

.eml attachments not supported here, but you can download an example .eml here: http://pastebin.com/bbjvVKA2

**Comment by jtagen** [comment]
This was closed without comment - does that mean it's fixed and slated for release?

**Comment by KodaKoder** [comment]
the problem is about parsing of html5 in AM
I know the issue now we are thinking how to solve it

**Comment by jtagen** [comment]
Closed again, does this mean it's fixed and in an upcoming release? I love Airmail, but am frustrated by one or two bugs, this is the most significant and common.

**Comment by KodaKoder** [comment]
we fix the facebook issue you can see it in beta 331

**Comment by martylouis** [comment]
Having a similar issue with the past versions and the latest beta release v2.6.1. For me it's only with [UberConference](http://uberconference.com) email. Specifically, "Join The Call" and "Run Test" buttons.

Not seeing this issue with other clients. I've tested Gmail (web), Apple Mail, Nylas N1, and Polymail.

Link to EML » http://d.pr/f/KNHa

Thanks!
