### ISSUE TITLE
Addresses from Exchange global address list do not get autocomleted

### ISSUE THREAD

**Issue by bkummel** [Airmail/Airmail_Public#194]
Addresses from the Exchange global address list are only viewable via the Global Address List window. In that window, addresses can be added to Airmail's database on an address-by-address basis. However, I'd expect Airmail to autocomplete addresses from the Global Address List automatically.

**Comment by agileminor** [comment]
Is this fixed in the released version, or just beta release? We are trying to use Airmail v2.0.2 with an exchange server and not seeing Airmail do any autocompletion of email addresses.

**Comment by arnab** [comment]
I just installed Airmail3. I can confirm that this is not working.

Typing a name into the `To:` field while composing only suggests contacts that Airmail has **seen before**, not from the Exchange global address list.

Also [this thread from Airmail forum](http://feedback.airmailapp.com/forums/274948-airmail-mac-3-x/suggestions/5408234-search-exchange-global-address-list-from-to-field) suggests that this got broken on Airmail3?
