### ISSUE TITLE
Emails cut off!

### ISSUE THREAD

**Issue by greiss122** [Airmail/Airmail_Public#203]
Sometimes, when I am scrolling in a long or long-ish email, the rest of the email is blank and white. I can see the rest by clicking and dragging above the white part, which then lets me see the bottom of the email but not the top. It's hard to explain, but here is a screen recording I made of the issue. First is the beginning of the message, then I scroll down, then I drag down. Help!
This is very annoying. 
Thanks!
http://www.youtube.com/watch?v=NwnL75C_Wjo

**Comment by renestalder** [comment]
fyi problem still exists

**Comment by zachwood** [comment]
Why did this get closed? It doesn't appear to be fixed (I'm on v2.6.1). 

This duplicate issue was also closed with no apparent resolution: https://github.com/Airmail/Airmail_Public/issues/114
