### ISSUE TITLE
Via Tender: Save to Evernote doesn't include attached PDFs

### ISSUE THREAD

**Issue by Bloophub** [Airmail/Airmail_Public#206]
Assigned to [Airmail Beta 227 #140](http://airmail.tenderapp.com/discussions/airmail-beta-227/140-save-to-evernote-doesnt-include-attached-pdfs). As reported in Tender:

<blockquote><p>Sending a message to Evernote with two PDFs and what I got
is:</p></blockquote>

**Comment by rickwagenaar** [comment]
I have the some issue. Only the content of the mail is sent to Evernote, but the attachments are not saved to Evernote.
