### ISSUE TITLE
Unable to reply an email - Illegal attachment error when no attachment in the mail

### ISSUE THREAD

**Issue by kkannan-carecloud** [Airmail/Airmail_Public#248]
Received a "Cannot send mail error Re: CENTRAL-4100 Attempted to send a message with an illegal attachment." error upon replying a email chain.

The email does not contain any illegal attachment. The only attachment that I can see is the the image that people use in the signature (a .jpg) file.

I was able to reply the email chain from gmail but not in Airmail Beta.
What is legal in gmail is illegal in Airmail Beta ?

I suspect that the illegal check logic in Airmail Beta blindly thinks a signature image as an illegal attachment.

**Comment by codesidekick** [comment]
Take a look at https://support.google.com/mail/answer/6590?hl=en to see supported files for attachment. I got this error when emailing a tar.gz file as GMAIL says you cannot use an archive within an archive as an attachment.
