### ISSUE TITLE
Airmail Keeps freezing and crash running OS X 10.8.5

### ISSUE THREAD

**Issue by Bmxbaby1** [Airmail/Airmail_Public#259]
My airmail keeps freezing and crashing did not have this problem with my other mail clients. It keeps freezing and I have to do force shutdown. Anyone know how to fix this issue its happening a few times a day.

**Comment by alxndr** [comment]
Happening to me several times a week, Airmail 2.0.3 (286), OS X 10.8.5

**Comment by Bmxbaby1** [comment]
Hi Alxndr I have been running the Airmail Beta 12 and for now it seems to be OK. If you haven't been running the Beta version you might try downloading that and running it seems to be OK. And when the new Beta versions come out I usually keep the last working version saved just in case the new one is buddy. Hope that helps

**Comment by alxndr** [comment]
Have been using the Beta build 289 for a couple days, but it just crashed/hid itself again.

It remains "running" according to Finder, and clicking its icon in the Dock switches focus to the app, with the "Airmail Beta" menu responding normally. However no windows are visible, and trying to "Show all windows" brings up an "Airmail" label like expected, but with no window to click on.

I've been quitting and restarting Airmail.
