### ISSUE TITLE
STKeychainErrorDomain error -60005

### ISSUE THREAD

**Issue by reuvenf** [Airmail/Airmail_Public#27]
Airmail does not save email passwords. Every time I restart the application it looses all the passwords. If I go and add the password again I receive a error: 
Cannot save password for account myaccount@gmail.com The operation couldn’t be completed. 
STKeychainErrorDomain error -60005.
Then it starts working again till I restart the application.

Please help.

**Comment by reuvenf** [comment]
Hi,

I hopped the version 2.0 will resolve this issue. But it does not. None of the solutions above that worked perviously are working now. If this is not fixed ASAP I'll have to drop this application and move back to Apple Mail or Thunderbird. 

I like Airmail, and not resolving this issue makes me extremely unhappy and forces me to stop using it.

Please let me know when this can be fixed.

Thank you.

**Comment by zapnap** [comment]
Just added a new account in latest Airmail 2. Same exact problem. Basically makes the application unusable. Have tried the suggestions above but no matter what I do I continue to get the same prompt. Guess I'll be hunting for a new mail client as the Airmail team doesn't seem to be addressing this :(.

**Comment by itsalexjones** [comment]
I'm also having the same problem in Airmail 2 after forking out to upgrade from Airmail 1 (which I can't say I was too please about), if it doesn't get fixed soon i'll have to request a refund for a product that does not function as advertised.
