### ISSUE TITLE
Copying an email message gives "mailto" link

### ISSUE THREAD

**Issue by danitaz** [Airmail/Airmail_Public#306]
If there is an email address in a message, and I want to copy it to use in the cc: field, it copies the "mailto" tag and results in an invalid email address.  AirMail should handle this better I think!

Thanks.

Danita

**Comment by scootersi** [comment]
I am seeing this same issue. Clicking any email address displays a "copy link" context menu. Selecting this and then pasting into with the address fields or body of an email produces a mailto:example@com email address that cannot be used.

This seems like a common workflow am I missing something?

Using Airmail version 3.0 (367) and OSX 10.11.4
