### ISSUE TITLE
"Local Sent" folder does not sync with server Sent Mail folder for iCloud account

### ISSUE THREAD

**Issue by briburt** [Airmail/Airmail_Public#340]
To repro:

1. Set up iCloud account using defaults.
2. Send a message using the iCloud account.

Result: Message is sent, but copy of sent message is stored only in the Local Sent folder and is not copied to the server's Sent Mail folder.

Expected Result: Message is sent, and copy of sent message is stored in the server's Sent Mail folder and, once copied, deleted from the Local Sent folder.

**Comment by librae8226** [comment]
Up. Same with Gmail and another POP account.
Any suggestions/ideas?

Thanks,
Librae
