### ISSUE TITLE
SMTP Test Failed

### ISSUE THREAD

**Issue by artimarkov** [Airmail/Airmail_Public#344]
"The settings are not valid:
Account check failed because the account is invalid."

The message is shown while I tried to setup my smtp account at "Yandex.ru" server.

Config params:
server: smtp.yandex.ru
security: SSL
port: 465

Also I tried to connect to port 25 or 587 without SSL but the same message is shown.

The Mac OS Mail.app is working fine with that server.

Using: AirMail Beta Version 1.3.2 (231)

**Comment by AndrewJMcCarthy** [comment]
So, I had this same issue on Zoho. It turns out that Zoho disabled SSL3, and thats what Airmail uses for SSL SMTP connections. You need to change over to Start TLS, and set it to port 587. Worked for me.

**Comment by Poliuk** [comment]
Thanks Andew, that solved my problem with Zoho!

**Comment by orlando** [comment]
@AndrewJMcCarthy :+1: thanks for the tip, I had no idea why it wasn't working.

**Comment by nickbuddendotcom** [comment]
Still not working for me with Start TLS on port 587.

**Comment by nickbuddendotcom** [comment]
@Bloophub why is this closed when it still doesn't work?

**Comment by KodaKoder** [comment]
Zoho works with stmp 465 ssl login
http://d.pr/i/15fG

**Comment by nickbuddendotcom** [comment]
@KodaKoder 

Still broken with 465:
+ https://cloudup.com/cKy2i-HLbZr
+ https://cloudup.com/cSK3TcaGu3N (port auto)

**Comment by Bloophub** [comment]
http://d.pr/i/qSuy

**Comment by nickbuddendotcom** [comment]
@Bloophub with `login` both with/without port auto https://cloudup.com/cR49FwmMHBT

**Comment by KodaKoder** [comment]
are you under vpn?

**Comment by nickbuddendotcom** [comment]
@KodaKoder no, I've tried on a number of different networks.

**Comment by diessica** [comment]
@Bloophub's solution worked for me.

**Comment by KodaKoder** [comment]
nickbuddendotcom would you mind to try a version with imap logs?
