### ISSUE TITLE
inline images not shown when 'Autoload Remote Images' is disabled

### ISSUE THREAD

**Issue by SWW13** [Airmail/Airmail_Public#356]
If the option 'Autoload Remote Images' is disabled directly attached images (referenced in email) are not shown. Image placeholder is visible and context menu is working.

P.S.: The message "Show Images Yes / No / Always" is also not shown.

**Comment by jeffsenn** [comment]
Please fix this!

**Comment by SWW13** [comment]
Don't think they will ever do anything about it.

**Comment by jeffsenn** [comment]
Is this fixed? Or just arbitrarily closed? Or accidentally closed? (It looks like every open issue on here was closed about 3 hours ago....)

**Comment by KodaKoder** [comment]
http://d.pr/i/mNle ?

**Comment by jkintscher** [comment]
Setting `Autoload Remote Images` to true is not an actual fix for this bug. I have it disabled for several reasons and would like to only load images for emails I trust after opening them. For (some) inline images this is not possible though as the banner to manually load them

![](https://monosnap.com/file/nrgieGWS2oKVGgvB9kUJFeZ3IH9pAM.png)

does not show up. Could you at least elaborate why you are not prioritising this?
