### ISSUE TITLE
Issues with HTML signature (photo as attachment)

### ISSUE THREAD

**Issue by mattcaruso** [Airmail/Airmail_Public#378]
My company has custom email signatures designed to work with Mail.app.  We have an HTML generator that creates our signatures (with an image) as a Web Archive.  In Mail.app, you can navigate to the signatures folder in the system files and paste in that web archive.  Voila.  It works as an inline image that pulls from the server every time, never attaching the image to the email and always scaling it properly.

I used to use Sparrow and I was able to simply copy/paste the signature and it rendered beautifully.

When I copy/paste (either the final formatted text or the HTML itself), Airmail does not do it properly. It makes the logo enormous and attaches it to the email. 

Is there a folder where Airmail keeps signatures similar to Mail.app? 

Any advice?

**Comment by joelseneque** [comment]
This issue is happening for me.
The images in my signature show up as attachments for people
