### ISSUE TITLE
Unable to send attachments via Exchange Server

### ISSUE THREAD

**Issue by colinb4987** [Airmail/Airmail_Public#397]
Using both Beta v1.3.2 (231) and Beta v1.4 (232), I am unable to send emails from my Exchange account that have an attachment. Receiving is fine. Sending without an attachment is fine. Sending without an attachment, but with an image in a signature is also fine. No error messages in log, just endless sending before eventually timing out. 

As far as I am aware, we are using Exchange 2010. 

Does not seem to be isolated to just my system, see https://airmail.zendesk.com/entries/42911007

**Comment by Dom-** [comment]
I have the same problem. Can I know if you are going to solve this issue? Thanks.

**Comment by Dom-** [comment]
I have the same problem. Can I know if you are going to solve this issue? Thanks

**Comment by Tantalon** [comment]
I'm using Airmail 2.0.3 (286) with Exchange, and it's failing to send mails that contain attachments. I can request a test account if needed.

**Comment by FabianMeul** [comment]
Also having this issue with Airmail 2.0.3 (286) and Exchange.

**Comment by plchri** [comment]
I'm having the same problem. Using Airmail 2.1 (303) and Exchange.
Attaching a PDF I get:
Cannot send mail error test A connection failure occurred: SSL problem (Possible causes may include a bad/expired/self-signed certificate, clock set to wrong date)

Have not had this problem before.

**Comment by abubakar119** [comment]
I am having same problem unable to send any attachment but a mail without attachment can send. I am using Apple Mail version 8.2 and Exchange server 2010. If i am connected to office local server its working fine but when i am outside on other network i face this issue.

**Comment by Tantalon** [comment]
Has this been fixed?

**Comment by KodaKoder** [comment]
we need some console logs to check the problem
Please kindly provide your console.app log filtered by Airmail 
check the below link
http://support.airmailapp.com/post/95590607728/how-to-get-the-console-log

**Comment by MathsGrad** [comment]
I have this problem too, console log:

27/01/2016 00:35:10.831 Airmail 2[5721]: View <MessageRowView: 0x7fa8ed1cd380> - row: -1 has 4 views pointing at it that can't be found.
27/01/2016 00:35:10.832 Airmail 2[5721]: View <MessageRowView: 0x7fa8f64581a0> - row: -1 has 6 views pointing at it that can't be found.
27/01/2016 00:35:16.565 Airmail 2[5721]: [***ERROR***] HttpsPostData Error 0 lucinda.hadley@lancaster.ac.uk Error Domain=ASIHTTPRequestErrorDomain Code=1 "A connection failure occurred" UserInfo={NSLocalizedDescription=A connection failure occurred, NSUnderlyingError=0x7fa8ed63e340 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)"}}
27/01/2016 00:35:18.387 Airmail 2[5721]: [***ERROR***] HttpsPostData Error 0 lucinda.hadley@lancaster.ac.uk Error Domain=ASIHTTPRequestErrorDomain Code=1 "A connection failure occurred" UserInfo={NSLocalizedDescription=A connection failure occurred, NSUnderlyingError=0x7fa8ef6dade0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)"}}
27/01/2016 00:35:18.390 Airmail 2[5721]: [BLOOP_ERROR] EXCHANGE:Send Mail 215] Fw: Next Week's... lucinda.hadley@lancaster.ac.uk 0 2016-01-27 00:35:14 +0000 Err A connection failure occurred
27/01/2016 00:35:18.395 Airmail 2[5721]: [BLOOP_ERROR] MAIL COMPOSER:cannot send mail error Err A connection failure occurred

**Comment by MathsGrad** [comment]
Same problem, console log below - please reply.

27/01/2016 00:35:10.831 Airmail 2[5721]: View <MessageRowView: 0x7fa8ed1cd380> - row: -1 has 4 views pointing at it that can't be found.
27/01/2016 00:35:10.832 Airmail 2[5721]: View <MessageRowView: 0x7fa8f64581a0> - row: -1 has 6 views pointing at it that can't be found.
27/01/2016 00:35:16.565 Airmail 2[5721]: [***ERROR***] HttpsPostData Error 0 <email address here> Error Domain=ASIHTTPRequestErrorDomain Code=1 "A connection failure occurred" UserInfo={NSLocalizedDescription=A connection failure occurred, NSUnderlyingError=0x7fa8ed63e340 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)"}}
27/01/2016 00:35:18.387 Airmail 2[5721]: [***ERROR***] HttpsPostData Error 0 <email address here> Error Domain=ASIHTTPRequestErrorDomain Code=1 "A connection failure occurred" UserInfo={NSLocalizedDescription=A connection failure occurred, NSUnderlyingError=0x7fa8ef6dade0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)"}}
27/01/2016 00:35:18.390 Airmail 2[5721]: [BLOOP_ERROR] EXCHANGE:Send Mail 215] Fw: Next Week's... <email address here> 0 2016-01-27 00:35:14 +0000 Err A connection failure occurred
27/01/2016 00:35:18.395 Airmail 2[5721]: [BLOOP_ERROR] MAIL COMPOSER:cannot send mail error Err A connection failure occurred
