### ISSUE TITLE
Exchange folder sync not completing

### ISSUE THREAD

**Issue by edmartin123** [Airmail/Airmail_Public#398]
Version 1.3.2 (231)

Sync with Exchange server is not fully syncing.  I have a few large folders (although all email prior to 1/1/13 has been archived off of the server).  I have now tried setting up and allowing full sync 3 times (including complete uninstall of Airmail and data files).

For example, my Sent folder on the Exchange server contains 11,916 messages and dates back to 1/2/13.

**Comment by slajax** [comment]
Is anything I can do that would contribute to solving this? Happy to try.
