### ISSUE TITLE
Block Quotes not working (in markdown at least)

### ISSUE THREAD

**Issue by theleica** [Airmail/Airmail_Public#404]
Block quotes when using markdown aren't working.

If I try to add

`> add block quote here`

Then I do not get a quote. The html adds 

`<blockquote>add block quote here</blockquote>` 

to the HTML, but it doesn't format it correctly as it is missing 

`type="cite" class="clean_bq"` 

from the HTML, so that it parses as

`<blockquote type="cite" class="clean_bq">add block quote here</blockquote>` 

Please amend the markdown formatting to not just add the blockquote HTML but to add the required type and class.

**Comment by lazywei** [comment]
has this be solved yet? It seems the ">" not work on Gmail.

**Comment by TravisCrist** [comment]
I saw the same thing ">" does not properly reflect in Gmail. Has this issue been resolved?

**Comment by flomotlik** [comment]
@Bloophub any update on this? This is a quite important and central feature

**Comment by dansteingart** [comment]
Ping: still a problem in airmail 3.  Thanks.

**Comment by cro** [comment]
Ping: still a problem in Version 3.0.2 (377)

**Comment by juangamnik** [comment]
Why is this bug closed? Still having this issue in 375
