### ISSUE TITLE
Error messages in Airmail

### ISSUE THREAD

**Issue by caddisbug** [Airmail/Airmail_Public#407]
I love your app.  It's fantastic.  Today's it's been very buggy.  Every other email I receive an error message that says, "Cannot send mail error [it then lists the name of the email here] Unable to authenticate with the current session's credentials."  I am using google mail as my mail server working on a Mac PowerBook Pro running the latest build of Airmail on the latest rev of MacOS

**Comment by leroyg** [comment]
I also am getting this error. Has this been solved yet elsewhere? Thank you.
