### ISSUE TITLE
Cannot save password - error -60005 + Void password for account 

### ISSUE THREAD

**Issue by DarioAlbini** [Airmail/Airmail_Public#416]
Hello there,
everytime i try to save account's password i got twice this error:

"Cannot save password for account info@xxxxxx.com The operation couldn’t be completed. (STKeychainErrorDomain error -60005.)"

Screen: 
![screen shot 2014-03-14 at 16 22 08](https://f.cloud.github.com/assets/6952660/2422314/67a0688a-ab8d-11e3-8ece-81ad07a6a05a.png)

and after i re-enter all the passwords, at Airmail startup i got this other error:
"Void password for account" 

Screen: 
![screen shot 2014-03-14 at 16 24 44](https://f.cloud.github.com/assets/6952660/2422324/706d0158-ab8d-11e3-8b4b-fdff287077c3.png)

My Airmail version is: Version 1.3.2 (231)
And i'm running on: Mac OsX 10.9.2

**Comment by xarquid** [comment]
And this bug is back ^^ And @DarioAlbini is correct, AirMail CANNOT save gmail/google passwords in the keychain.

**Comment by DarioAlbini** [comment]
Happy not be alone, @xarquid. :)
Unfortunately i had to give up. In the end i had a good and consistent support from Arimail team, but after several tries they too was forced to raise white flag. 
Currently it is seems there are no solutions, hope you'll have better luck.

**Comment by xarquid** [comment]
@DarioAlbini I removed my gmail accounts from both the keychain and Airmail. Afterwards, I added both accounts back to Airmail and the passwords "stuck."

**Comment by swisschris** [comment]
Same Problem here. I tried everything. It works with one iMac, the other one never worked.

**Comment by D3MZ** [comment]
+1 to the issue for me.

**Comment by swisschris** [comment]
I solved the issue: i had the keychains saved in Dropbox (with symlink). Airmail didn't like that.

**Comment by DarioAlbini** [comment]
Same here. How did you solved swisschris? Did had to give up keychains sync via Dropbox?

**Comment by swisschris** [comment]
Yes, I changed to synchronization with iCloud.

**Comment by zapnap** [comment]
Sadly still seeing this issue :(.

**Comment by zapnap** [comment]
In case anyone is curious: I resolved this by resetting my default keychain in keychain access (preferences menu, general). After re-authenticating and restarting Airmail, I can once again save passwords. Woot.
