### ISSUE TITLE
IMAP sync problem

### ISSUE THREAD

**Issue by janslu** [Airmail/Airmail_Public#426]
I have a problem with a Courier server IMAP account. It syncs only last 20 messages from inbox, even though there's more than 11000 messages visible either through webmail or other email clients (apple mail and thunderbird). 

I get the following error in system log:

16/03/14 16:05:44,792 AirMail Beta[52454]: [***ERROR***] FetchFolder no array [11335 11374] POS -1] ROWID 26] INBOX st:1 sel:1email@domain Error Domain=MCOErrorDomain Code=3 "Unable to parse response from server." UserInfo=0x608000e6dac0 {NSLocalizedDescription=Unable to parse response from server.} 

Any way I can help you track the problem down?

**Comment by ragboy** [comment]
I have this same issue that I reported via a chat support and uploaded logs. Still not resolved with 289. The problem started when I switched from gmail as my email host to an internal Zarafa IMAP host. All of my other clients, and many others I have tested (mac mail, mail mate, thunderbird, postbox, mail pilot, unibox, and several others) seem to work fine with the new server. Only Airmail does not work, email will not sync with numerous errors:

2/10/15 12:20:20.693 PM Airmail Beta[46838]: [***ERROR***] rgarcia@bighead.net CheckAll zend-monitor Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo=0x608000663f80 {NSLocalizedDescription=The requested folder does not exist.  Folder selection failed}
2/10/15 12:20:20.708 PM Airmail Beta[46838]: [***ERROR***] CheckFolderNgx Expunge POS -1] ROWID 9] INBOX st:1 sel:1 rgarcia@bighead.net Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo=0x618000273bc0 {NSLocalizedDescription=The requested folder does not exist.  Folder selection failed}
2/10/15 12:20:20.722 PM Airmail Beta[46838]: [***ERROR***] CheckFolderNgx Cannot FolderInfo POS -1] ROWID 9] INBOX st:1 sel:1 rgarcia@bighead.net Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo=0x618000679240 {NSLocalizedDescription=The requested folder does not exist.  Folder selection failed} IMAP > Name:1)[Operation_1] rgarcia@bighead.net 
2/10/15 12:20:20.722 PM Airmail Beta[46838]: [***ERROR***] rgarcia@bighead.net CheckAll Inbox INBOX Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo=0x618000679240 {NSLocalizedDescription=The requested folder does not exist.  Folder selection failed}
2/10/15 12:20:20.722 PM Airmail Beta[46838]: [***ERROR***] Error StartUpdate FOLDERS rgarcia@bighead.net Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo=0x618000679240 {NSLocalizedDescription=The requested folder does not exist.  Folder selection failed}
2/10/15 12:20:22.287 PM Airmail Beta[46838]: [***ERROR***] FetchFolderNgx Cannot FolderInfo POS -1] ROWID 29] keys st:0 sel:1 rgarcia@bighead.net Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo=0x600000a6f180 {NSLocalizedDescription=The requested folder does not exist.  Folder selection failed}
2/10/15 12:20:22.287 PM Airmail Beta[46838]: [BLOOP_ERROR] FETCH:Fetch in keys Err The requested folder does not exist.  Folder selection failed
2/10/15 12:20:25.293 PM Airmail Beta[46838]: [***ERROR***] FetchFolderNgx Cannot FolderInfo POS -1] ROWID 35] zend-monitor st:0 sel:1 rgarcia@bighead.net Error Domain=MCOErrorDomain Code=11 "The requested folder does not exist.  Folder selection failed" UserInfo=0x61000067c780 {NSLocalizedDescription=The requested folder does not exist.  Folder selection failed}
2/10/15 12:20:25.294 PM Airmail Beta[46838]: [BLOOP_ERROR] FETCH:Fetch in zend-monitor Err The requested folder does not exist.  Folder selection failed

"Unable to parse response from server" is also common in these logs.
