### ISSUE TITLE
Mail server doen't send any more

### ISSUE THREAD

**Issue by arjan2104** [Airmail/Airmail_Public#459]
I've my own site with a mail server. But when I send a mail to someone it doesn't work.
I get some kind of a pop-up what says:

Cannot send mail error test Sending messages is not allowed on this server.

How can I fixe this?

**Comment by homarsanchez** [comment]
Same here. Are there any ideas?

**Comment by ceah** [comment]
I've just started having this problem as well. Any updates on how to fix? Thanks

**Comment by Lockzi** [comment]
Happens to me too, very annoying...
Any solutions?
