### ISSUE TITLE
Meeting invites from outside my organisation do not give me the accept/decline option

### ISSUE THREAD

**Issue by mrinlumino** [Airmail/Airmail_Public#471]
Whenever I receive an meeting invite from outside my organisation (and exchange server) I do not get the option to accept/decline the meeting as I do when I get an internal invite. I see the meeting attached to the email but I do not get the buttons to accept or decline the meeting. If I double click on the attached invite the meeting is opened in my iCal app but will be added to the wrong calendar (I have both exchange and iCloud calendars active in my iCal app.

**Comment by mkrump** [comment]
Having the same issue. Any details on how to resolve this?
