### ISSUE TITLE
Didn't open URL's in email

### ISSUE THREAD

**Issue by liubarets** [Airmail/Airmail_Public#474]
I had received the letter with some URLs. One URL was opened, others - no.

URL for first link: http://usndr.com/ru/mail_link_tracker?hash=513tf89po14antk4wm8cu3wcbi5r48kkmh3dcxji3dn9mwsy83yxg7og9mwrywfdhnmu3adgj85g7c&url=http%253A%252F%252Fdepositphotos.com%252F42046363%252Fstock-illustration-Hipster-character-illustration.html%253Futm_source%253Dsubscription%2526utm_medium%253Demail%2526utm_campaign%253Dru-free45%2526utm_term%253Dbutton

URLs for others links: applewebdata://DDCFDC14-508C-426F-AFCF-3FEBF70BD9EA/%20http://usndr.com/ru/mail_link_tracker?hash=5xydmjxir4j5w5k4wm8cu3wcbi5r48kkmh3dcxjzzxwqcs9ss9o56oy1r591679571jbug4eacb9pk&url=http%253A%252F%252Fdepositphotos.com%252Fsubscribe.html%253Futm_source%253Dsubscription%2526utm_medium%253Demail%2526utm_campaign%253Dru-free45%2526utm_term%253Done-month

applewebdata://DDCFDC14-508C-426F-AFCF-3FEBF70BD9EA/%20http://usndr.com/ru/mail_link_tracker?hash=5z4cidyfurgzbdk4wm8cu3wcbi5r48kkmh3dcxjoertanoa7xnmkagrk6u6cumt9sf63coe4ucc761&url=http%253A%252F%252Fdepositphotos.com%252Fsubscribe.html%253Futm_source%253Dsubscription%2526utm_medium%253Demail%2526utm_campaign%253Dru-free45%2526utm_term%253Dthree-month

etc

But in unisender adminpanel this URLs similar to each other http://take.ms/2LJ2O 

Newsletter scr https://dl.dropbox.com/s/3b95deuiab927k6/Screenshot_20140325_111411_20140325_111559.png

**Comment by twisst** [comment]
Hi, I'm seeing this issue in Airmail 2.6.1 on OSX 10.11.3. The newsletter in which the links are unclickable, used to work fine until recently, so it seems the problem returned with the newest Airmail version.

**Comment by twisst** [comment]
@Bloophub should I open a new issue?

**Comment by isartis** [comment]
I'm also having this issue. It appear to me after changing to Airmailapp as default Mail app on Mac. 
Version 2.6.1 (353)

**Comment by Albert99** [comment]
The same problem at july of 2016.

**Comment by twisst** [comment]
Solved here, thanks to the latest version (3.0).
