### ISSUE TITLE
Switch Rich Text / Plain Text Composer

### ISSUE THREAD

**Issue by fenderle** [Airmail/Airmail_Public#510]
You can switch the editor in the composer from Rich Text to Plain Text using the Composer -> Plain Text Composer menu, but there's no menu item to switch to the other direction. This is particularly annoying if you use the Plain Text Composer as your default setting and want to write a Rich Text mail once in a while.

Maybe the menu item can swap from Plain Text Composer to Rich Text Composer when the Plain Text Composer is active and vice versa.

**Comment by rasmusbrandt** [comment]
This is a feature that I really miss as well!

**Comment by rasmusbrandt** [comment]
Has this been implemented? :grinning:

**Comment by spointbr** [comment]
+1
