### ISSUE TITLE
Exchange Server: Cannot mark message as READ when offline

### ISSUE THREAD

**Issue by A-Coward** [Airmail/Airmail_Public#522]
I have downloaded messages from an Exchange server on my laptop when connected to an internal network (work).  I now disconnect from the internal network and read my mail when connected to another network (coffee shop) where I no longer have connectivity to the Exchange server.  During this time I cannot mark my mail messages as read.

Now, if I have no network connectivity at all, I can mark the messages as read.  However, once I connect to another network with no Exchange server access, the message will again show up as unread.  I can only persistently mark a message as unread if it is marked unread while I have connectivity to the Exchange server.

This was noticed on all App Store version including the current version 1.3.3 (237).

**Comment by mspenguinette** [comment]
I still have the issue in Version 2.1 (303). It is beyond frustrating.

I haven't figured out what ends up making them end up read a day or two later.
