### ISSUE TITLE
Embedded/inline image autoload problem

### ISSUE THREAD

**Issue by bsibsi** [Airmail/Airmail_Public#569]
When autoload remote images is turned off, the local images (embedded inline images inside message body, linked with img src="cid:imgname") didn't show up as well. I can only get them loaded and displayed by pressing CMD-J. These images should be loaded and shown automatically, without any user interaction.

**Comment by jeffsenn** [comment]
Me too!  Please fix this!!

**Comment by jeffsenn** [comment]
Note: this is a duplicate of #356
