### ISSUE TITLE
CPU use extremely intensive in Yosemite

### ISSUE THREAD

**Issue by CameronBanga** [Airmail/Airmail_Public#625]
I know this is Yosemite beta one, which I'm using at my own risk, but wanted to file this in case it's rare/isolated. 

Seeing extremely high CPU usage by Airmail, which occurs each time I open it, about 30 seconds to a minute after opening. I've attached a Activity Monitor sample to check out. It's kicking up the fans on my Retina MBP with 16GB RAM pretty hard. Turned off GPU acceleration but that hasn't helped (although I'm not sure it would, but gave it a try)

http://cameronbanga.com/media/AirmailSample.txt

**Comment by techhelper1** [comment]
Well... it's not for me.
