### ISSUE TITLE
Facebook comment emails links disabled?

### ISSUE THREAD

**Issue by victorminator** [Airmail/Airmail_Public#628]
Not quite sure why but when I get Facebook notification emails, specifically the attached type, the See Comment box is disabled from being clickable and is instead acting as if it's a text box, i.e. the cursor turns into a typing cursor and I can't click. This behaviour is not happening within Gmail itself.
Running MAS version 1.3.3.

![screen shot 2014-07-10 at 7 56 13 am](https://cloud.githubusercontent.com/assets/410897/3548644/693bc968-08b3-11e4-88e4-26b3baf132c7.png)

**Comment by timkelty** [comment]
Any update? This is the one thing that drives me nuts about Airmail!

**Comment by victorminator** [comment]
I'm baffled by the lack of updates. Paid the expensive upgrade and got a near-exact product functionality and code-wise. I've almost given up on this mail client. I'll either switch back to Mail or hope for a new better client soon.

**Comment by hoblin** [comment]
Same for me ![buggy mail](https://www.evernote.com/shard/s22/sh/3c442380-aa75-4314-96bf-ed2728abe1c3/2db82e57b209ea30c03d5ea20f5a2193/res/1103806f-7816-4b21-92fa-d12d53d04892/skitch.png)

**Comment by hoblin** [comment]
Does that mean you fixed this issue or just closed bugtracker? =)

**Comment by KodaKoder** [comment]
is a problem about html and tidy validation thanks

**Comment by timkelty** [comment]
Big update pushed today (2.5) and this still isn't fixed :(.
Very frustrating!

**Comment by KodaKoder** [comment]
working on it just now will be in the next release next week

**Comment by timkelty** [comment]
Great news, thanks!

**Comment by timkelty** [comment]
Tested the beta, working great. Thanks for addressing this!
