### ISSUE TITLE
Can't delete message in the Thread

### ISSUE THREAD

**Issue by grudek** [Airmail/Airmail_Public#64]
Hi, I try to delete earliest messages in the message thread pressing (x), doing nothing just a trash sound, if I am using drop-down menu, it disappear, but, not really trashed, when I leaving Thread to another messages in Inbox, and coming back to this Thread, message reappear. Please note, that on the left side in Inbox, count of the messages in the thread stay the same all time. It is Gmail IMAP. Please check screenshots: 1. I did nothing, 2. I deleted last message in the thread, 3. Coming back to the thread.

![screen shot 2014-01-13 at 17 41 49](https://f.cloud.github.com/assets/6390800/1901785/bee6f044-7c69-11e3-8a2d-a133f806480f.png)
![screen shot 2014-01-13 at 17 42 09](https://f.cloud.github.com/assets/6390800/1901787/c53cc946-7c69-11e3-8a8f-b582fdfe3008.png)
![screen shot 2014-01-13 at 17 43 21](https://f.cloud.github.com/assets/6390800/1901791/cea6978c-7c69-11e3-8991-25ade588e2b1.png)
![screen shot 2014-01-13 at 17 43 32](https://f.cloud.github.com/assets/6390800/1901793/d3ba716c-7c69-11e3-8aa8-d949946d0a91.png)
![screen shot 2014-01-13 at 17 43 47](https://f.cloud.github.com/assets/6390800/1901796/d865e804-7c69-11e3-8ee8-8eb90a26fadc.png)

AirMail 1.3.1 (223), Mac OS 10.9.1

**Comment by SeanDeLaSean** [comment]
Same problem here. Airmail 2.0.3 Mac OS X 10.10.2

**Comment by xilopaint** [comment]
Is there already a solution for this issue?
