### ISSUE TITLE
The issue with long subject in Russian

### ISSUE THREAD

**Issue by bolobolo27** [Airmail/Airmail_Public#646]
Hello,

I found the issue with the subject with Russian characters. 

If I send the message with subject «Тестовое письмо. Тестовое письмо. » the recipients get the message with the same subject - is’t OK.

If I send the message with subject «Тестовое письмо. Тестовое письмо. Тестовое письмо.» (more Russian symbols in the Subject) the recipients get the message with the subject «=?utf-8?Q?=D0=A2=D0=B5=D1=81=D1=82=D0=BE=D0=B2=D0=BE=D0=B5_=D0=BF=D0=B8=D1=81=D1=8C=D0=BC=D0=BE._=D0=A2=D0=B5=D1=81=D1=82=D0=BE=D0=B2=D0=BE=D0=B5_=D0=BF=D0=B8=D1=81=D1=8C=D0=BC=D0=BE._=D0=A2=D0=B5=D1=81=D1=82=D0=BE=D0=B2=D0=BE=D0=B5_=D0=BF=D0=B8=D1=81=...» and it’s not OK.

Could you fix the issue ? Thank you.

**Comment by Bloophub** [comment]
I need a Sample mail of this in EML format
