### ISSUE TITLE
imap test failed with Zoho

### ISSUE THREAD

**Issue by jordansteeves** [Airmail/Airmail_Public#655]
I have tried many iterations but it seems imap doesn't work with Zoho.

**Comment by josedulanto** [comment]
Hello!

I tried the settings Zoho describes in their user guide (https://www.zoho.com/mail/help/imap-access.html) with no luck, however I could connect to my email account (using my own domain) with these settings:

Incoming IMAP: imap.zoho.com
Port: 993 TLS NONE

Sending SMTP: smto.zoho.com
Port: 465 TLS LOGIN

Here are the user details of the account I tested the above settings with:
![image](https://cloud.githubusercontent.com/assets/51538/6540478/0103079e-c465-11e4-8da9-736b6960ca05.png)

Hope this helps! :)

**Comment by nickbuddendotcom** [comment]
Airmail is not working with Zoho IMAP. I can connect another client (Thunderbird) using identical credentials, but airmail never connects.

**Comment by Bloophub** [comment]
Yes should work, Please check the latest beta, http://airmailapp.com/beta

**Comment by nickbuddendotcom** [comment]
@Bloophub No, this does not work with the download from http://airmailapp.com/beta. Identical issue.

**Comment by nickbuddendotcom** [comment]
![airmail](https://cloud.githubusercontent.com/assets/2310565/9214853/7dae5e6e-40d5-11e5-8aee-59985dc430c0.gif)

**Comment by Bloophub** [comment]
please leave the port to auto and not set any number same result?

**Comment by Bloophub** [comment]
Can we have a test account?

**Comment by KodaKoder** [comment]
http://d.pr/i/15fG
