### ISSUE TITLE
Safari launches every time I control-click on a word in message

### ISSUE THREAD

**Issue by chitsaou** [Airmail/Airmail_Public#663]
Hi,

I have Airmail Beta Version 2.0 (301) on OS X 10.10.3 (14D136)

Every time I right-click on a word in any message Safari launches.

## Reproduction Steps

1. Open a message in Airmail
2. Right-click on any word to show the context menu

## Expected

* Context menu shows up, and nothing else happens.

## Actual

* Context menu shows up, and Safari launches.

In Console.app there is such message every time this issue happens:

```
2015/04/20 23:36:48.409 pkd[448]: enabling pid=21117 for plug-in com.apple.share.System.add-to-safari-reading-list(329) BAD83C39-341E-4731-9BB7-9A704169FC05 /System/Library/PrivateFrameworks/ShareKit.framework/Versions/A/PlugIns/SystemAddToReadingList.appex
```

When I quit Safari it shows:

```
2015/04/20 23:41:09.858 CoreServicesUIAgent[16698]: unexpected message <OS_xpc_error: <error: 0x7fff78de5c60> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x7fff78de5f70> { length = 18, contents = "Connection invalid" }
}>
2015/04/20 23:41:09.874 Airmail Beta[21117]: plugin com.apple.share.System.add-to-safari-reading-list interrupted
2015/04/20 23:41:09.875 Airmail Beta[21117]: plugin com.apple.share.System.add-to-safari-reading-list interrupted
2015/04/20 23:41:09.876 Airmail Beta[21117]: plugin com.apple.share.System.add-to-safari-reading-list interrupted
2015/04/20 23:41:10.271 CoreServicesUIAgent[16698]: unexpected message <OS_xpc_error: <error: 0x7fff78de5c60> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x7fff78de5f70> { length = 18, contents = "Connection invalid" }
}>
2015/04/20 23:41:10.275 com.apple.xpc.launchd[1]: (com.apple.WebKit.Networking.AC717D3F-5FAC-4E75-BA3E-51949BFB1A4F[21208]) Service exited with abnormal code: 1
2015/04/20 23:41:10.280 com.apple.xpc.launchd[1]: (com.apple.WebKit.WebContent.99795C5B-BEC5-4940-A54B-85E7B70E9297[21209]) Service exited with abnormal code: 1
```

Hope these messages help you resolve the problem.

**Comment by dinomite** [comment]
I see this, too—when I right click to copy the link, Safari opens up and the link is added to the Reading List.  I don't use Safari or its Reading List so this behavior is frustrating.

**Comment by chumbothewhale** [comment]
I get the exact same error.

**Comment by lonniev** [comment]
@Bloophub would you care to comment on the resolution? Fortunately, I do not often right-click in email but when I do, this behavior is surprising and annoying. I intentionally choose not to use Apple Mail and Safari and it is frustrating that Airmail 2 so strongly wants to send its users to Safari.

**Comment by newgrounds** [comment]
I know this is an old post. This isn't fixed in the app store version, but it has been fixed in the beta versions. You can download those if you can't wait for the app store release. I bet a new version will be uploaded to the app store shortly after El Capitan is released.
