### ISSUE TITLE
Broad privileges when logging into Gmail

### ISSUE THREAD

**Issue by publicarray** [Airmail/Airmail_Public#668]
I am using Airmail Version 2.5 (321) and I was wondering why airmail needs such broad privileges on my Gmail account. I don't want Airmail to be able to see my fellow uni students / staff email addresses. Or even group subscriptions across the entire domain. I don't see any reason for these.
![airmail 321](https://cloud.githubusercontent.com/assets/5497998/9358950/063816ce-46d2-11e5-9344-3531c0a16895.png)
![screen shot 2015-08-20 at 12 12 56 am](https://cloud.githubusercontent.com/assets/5497998/9358851/7d4c9880-46d1-11e5-868e-0ce01a1eb1d8.png)
![screen shot 2015-08-20 at 12 13 09 am](https://cloud.githubusercontent.com/assets/5497998/9358852/7d4cc6d4-46d1-11e5-8e52-ba7c691b960a.png)

**Comment by KodaKoder** [comment]
is read only access, we implemented the directory search
now you domain contacts will appear when you type in the composer

**Comment by publicarray** [comment]
You addressed the first of the two permissions. Having domain contacts is well and good for a small organisation but its not very useful for over 40,000 email addresses.

**Comment by Bloophub** [comment]
Keep optional is possible. The search is based on what you type. is it works for you?

**Comment by publicarray** [comment]
I have't enabled it since for me this is a privacy concern.

**Comment by Bloophub** [comment]
This is quite odd, we don't have access to your data, is just the app that is searching for your contacts and suggest on the composer window.

**Comment by publicarray** [comment]
Oh sorry, I always assumed that OAuth requires a Server connection. Thanks for the clarification.

**Comment by Bloophub** [comment]
Ok. Airmail is a client only, is pretty scaring that you felt we had access to that. That message means that potentially the app can edit your contacts so you must give approval, but at the moment Airmail onky read the contact to suggest them in the composer.

**Comment by publicarray** [comment]
Thanks, I am happy with all but one of the permissions now. why does airmail need to see the group subscriptions for the domain?

**Comment by Bloophub** [comment]
I guess that we would implement to send a message to the full group, but is no yet implemented. we can get rid for the moment thanks for pointing this

**Comment by publicarray** [comment]
I am glad this is cleared up now, thanks.
